-- Script for creating database and tables for use with Geonorge nedlasting-api

CREATE TABLE PROJECTION (CODESPACE VARCHAR(512) NOT NULL, NAME VARCHAR(512) NOT NULL, SRID INTEGER NOT NULL, PRIMARY KEY (SRID))
;

CREATE TABLE DATASET (ACCESS_CONSTRAINT VARCHAR(1024) NULL, DATASET_ID NUMBER NOT NULL, FME_CUT_URL VARCHAR(2048) NULL, MAP_SELECTION_LAYER VARCHAR(1024) NULL, MAX_AREA INTEGER NULL, METADATA_UUID VARCHAR(64) NULL, SUPPORTS_AREA_SELECTION INTEGER NULL, SUPPORTS_FORMAT_SELECTION INTEGER NULL, SUPPORTS_POLYGON_SELECTION INTEGER NULL, SUPPORTS_PROJECTION_SELECTION INTEGER NULL, TITLE VARCHAR(1024) NULL, PRIMARY KEY (DATASET_ID))
;

CREATE TABLE DATASET_FILE (AREA_CODE VARCHAR(32) NULL, AREA_NAME VARCHAR(1024) NULL, AREA_TYPE VARCHAR(256) NULL, DATASET_ID NUMBER NOT NULL, FILE_DATE TIMESTAMP NOT NULL, FILE_ID VARCHAR(64) NOT NULL, FILE_NAME VARCHAR(1024) NULL, FORMAT_NAME VARCHAR(1024) NULL, FORMAT_VERSION VARCHAR(32) NULL, SRID INTEGER NOT NULL, URL VARCHAR(2048) NULL, PRIMARY KEY (DATASET_ID, FILE_ID))
;

CREATE TABLE DOWNLOAD_ORDER (EMAIL VARCHAR(512) NULL, ORDER_ID NUMBER NOT NULL, REFERENCE_NUMBER VARCHAR(64) NOT NULL, START_TIME TIMESTAMP NOT NULL, PRIMARY KEY (ORDER_ID))
;

CREATE TABLE API_USER (PASSWORD_SHA512 VARCHAR(128) NULL, USERNAME VARCHAR(128) NOT NULL, PRIMARY KEY (USERNAME))
;

CREATE TABLE DATASET_EXTERNAL_PARAMETER (DATASET_ID NUMBER NOT NULL, PARAMETER_NAME VARCHAR(1024) NOT NULL, PARAMETER_VALUE VARCHAR(1024) NOT NULL, PRIMARY KEY (DATASET_ID, PARAMETER_NAME))
;

CREATE TABLE DOWNLOAD_ITEM (COORDINATES CLOB NULL, EXTERNAL_JOB_ID VARCHAR(1024) NULL, FILE_ID VARCHAR(64) NOT NULL, FILE_NAME VARCHAR(1024) NULL, METADATA_UUID VARCHAR(64) NULL, ORDER_ID NUMBER NOT NULL, ORDER_ITEM_ID NUMBER NOT NULL, SRID INTEGER NOT NULL, URL VARCHAR(2048) NULL, PRIMARY KEY (ORDER_ITEM_ID))
;

ALTER TABLE DATASET_FILE ADD FOREIGN KEY (SRID) REFERENCES PROJECTION (SRID)
;

ALTER TABLE DATASET_FILE ADD FOREIGN KEY (DATASET_ID) REFERENCES DATASET (DATASET_ID)
;

ALTER TABLE DATASET_EXTERNAL_PARAMETER ADD FOREIGN KEY (DATASET_ID) REFERENCES DATASET (DATASET_ID)
;

ALTER TABLE DOWNLOAD_ITEM ADD FOREIGN KEY (ORDER_ID) REFERENCES DOWNLOAD_ORDER (ORDER_ID)
;

CREATE SEQUENCE pk_api_user START WITH 200 INCREMENT BY 20
;

CREATE SEQUENCE pk_dataset START WITH 200 INCREMENT BY 20
;

CREATE SEQUENCE pk_dataset_external_parameter START WITH 200 INCREMENT BY 20
;

CREATE SEQUENCE pk_dataset_file START WITH 200 INCREMENT BY 20
;

CREATE SEQUENCE pk_download_item START WITH 200 INCREMENT BY 20
;

CREATE SEQUENCE pk_download_order START WITH 200 INCREMENT BY 20
;

CREATE SEQUENCE pk_projection START WITH 200 INCREMENT BY 20
;
