//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.05 at 08:37:03 AM CEST 
//


package no.geonorge.skjema.sosi.tjenestespesifikasjon.nedlastingapi._2;

import java.io.Serializable;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import no.kxml.rest._1.LinkListeType;


/**
 * <p>Java class for CapabilitiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CapabilitiesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="supportsProjectionSelection" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="supportsFormatSelection" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="supportsPolygonSelection" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="supportsAreaSelection" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="mapSelectionLayer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="_links" type="{http://www.kxml.no/rest/1.0}LinkListeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CapabilitiesType", propOrder = {
    "supportsProjectionSelection",
    "supportsFormatSelection",
    "supportsPolygonSelection",
    "supportsAreaSelection",
    "mapSelectionLayer",
    "links"
})
public class CapabilitiesType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected boolean supportsProjectionSelection;
    protected boolean supportsFormatSelection;
    protected boolean supportsPolygonSelection;
    protected boolean supportsAreaSelection;
    @XmlElement(required = true)
    protected String mapSelectionLayer;
    @XmlElementRef(name = "_links", namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", type = JAXBElement.class, required = false)
    protected JAXBElement<LinkListeType> links;

    /**
     * Gets the value of the supportsProjectionSelection property.
     * 
     */
    public boolean isSupportsProjectionSelection() {
        return supportsProjectionSelection;
    }

    /**
     * Sets the value of the supportsProjectionSelection property.
     * 
     */
    public void setSupportsProjectionSelection(boolean value) {
        this.supportsProjectionSelection = value;
    }

    /**
     * Gets the value of the supportsFormatSelection property.
     * 
     */
    public boolean isSupportsFormatSelection() {
        return supportsFormatSelection;
    }

    /**
     * Sets the value of the supportsFormatSelection property.
     * 
     */
    public void setSupportsFormatSelection(boolean value) {
        this.supportsFormatSelection = value;
    }

    /**
     * Gets the value of the supportsPolygonSelection property.
     * 
     */
    public boolean isSupportsPolygonSelection() {
        return supportsPolygonSelection;
    }

    /**
     * Sets the value of the supportsPolygonSelection property.
     * 
     */
    public void setSupportsPolygonSelection(boolean value) {
        this.supportsPolygonSelection = value;
    }

    /**
     * Gets the value of the supportsAreaSelection property.
     * 
     */
    public boolean isSupportsAreaSelection() {
        return supportsAreaSelection;
    }

    /**
     * Sets the value of the supportsAreaSelection property.
     * 
     */
    public void setSupportsAreaSelection(boolean value) {
        this.supportsAreaSelection = value;
    }

    /**
     * Gets the value of the mapSelectionLayer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMapSelectionLayer() {
        return mapSelectionLayer;
    }

    /**
     * Sets the value of the mapSelectionLayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMapSelectionLayer(String value) {
        this.mapSelectionLayer = value;
    }

    /**
     * Gets the value of the links property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LinkListeType }{@code >}
     *     
     */
    public JAXBElement<LinkListeType> getLinks() {
        return links;
    }

    /**
     * Sets the value of the links property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LinkListeType }{@code >}
     *     
     */
    public void setLinks(JAXBElement<LinkListeType> value) {
        this.links = value;
    }

}
