//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.05 at 08:37:03 AM CEST 
//


package no.geonorge.skjema.sosi.tjenestespesifikasjon.nedlastingapi._2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import no.kxml.rest._1.LinkListeType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.geonorge.skjema.sosi.tjenestespesifikasjon.nedlastingapi._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Area_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "Area");
    private final static QName _CanDownloadRequest_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "CanDownloadRequest");
    private final static QName _CanDownloadResponse_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "CanDownloadResponse");
    private final static QName _Capabilities_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "Capabilities");
    private final static QName _File_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "File");
    private final static QName _Format_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "Format");
    private final static QName _Order_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "Order");
    private final static QName _OrderArea_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "OrderArea");
    private final static QName _OrderLine_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "OrderLine");
    private final static QName _OrderReceipt_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "OrderReceipt");
    private final static QName _Projection_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "Projection");
    private final static QName _VersionResponse_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "VersionResponse");
    private final static QName _VersionResponseTypeLinks_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "_links");
    private final static QName _OrderReceiptTypeFiles_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "files");
    private final static QName _OrderLineTypeAreas_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "areas");
    private final static QName _OrderLineTypeFormats_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "formats");
    private final static QName _OrderLineTypeProjections_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "projections");
    private final static QName _FileTypeName_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "name");
    private final static QName _FileTypeFileId_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "fileId");
    private final static QName _FileTypeMetadataUuid_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "metadataUuid");
    private final static QName _FileTypeArea_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "area");
    private final static QName _FileTypeCoordinates_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "coordinates");
    private final static QName _FileTypeProjection_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "projection");
    private final static QName _FileTypeFormat_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "format");
    private final static QName _FileTypeStatus_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "status");
    private final static QName _CanDownloadResponseTypeMessage_QNAME = new QName("http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", "message");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.geonorge.skjema.sosi.tjenestespesifikasjon.nedlastingapi._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AreaType }
     * 
     */
    public AreaType createAreaType() {
        return new AreaType();
    }

    /**
     * Create an instance of {@link CanDownloadRequestType }
     * 
     */
    public CanDownloadRequestType createCanDownloadRequestType() {
        return new CanDownloadRequestType();
    }

    /**
     * Create an instance of {@link CanDownloadResponseType }
     * 
     */
    public CanDownloadResponseType createCanDownloadResponseType() {
        return new CanDownloadResponseType();
    }

    /**
     * Create an instance of {@link CapabilitiesType }
     * 
     */
    public CapabilitiesType createCapabilitiesType() {
        return new CapabilitiesType();
    }

    /**
     * Create an instance of {@link FileType }
     * 
     */
    public FileType createFileType() {
        return new FileType();
    }

    /**
     * Create an instance of {@link FormatType }
     * 
     */
    public FormatType createFormatType() {
        return new FormatType();
    }

    /**
     * Create an instance of {@link OrderType }
     * 
     */
    public OrderType createOrderType() {
        return new OrderType();
    }

    /**
     * Create an instance of {@link OrderAreaType }
     * 
     */
    public OrderAreaType createOrderAreaType() {
        return new OrderAreaType();
    }

    /**
     * Create an instance of {@link OrderLineType }
     * 
     */
    public OrderLineType createOrderLineType() {
        return new OrderLineType();
    }

    /**
     * Create an instance of {@link OrderReceiptType }
     * 
     */
    public OrderReceiptType createOrderReceiptType() {
        return new OrderReceiptType();
    }

    /**
     * Create an instance of {@link ProjectionType }
     * 
     */
    public ProjectionType createProjectionType() {
        return new ProjectionType();
    }

    /**
     * Create an instance of {@link VersionResponseType }
     * 
     */
    public VersionResponseType createVersionResponseType() {
        return new VersionResponseType();
    }

    /**
     * Create an instance of {@link AreaListe }
     * 
     */
    public AreaListe createAreaListe() {
        return new AreaListe();
    }

    /**
     * Create an instance of {@link CanDownloadRequestListe }
     * 
     */
    public CanDownloadRequestListe createCanDownloadRequestListe() {
        return new CanDownloadRequestListe();
    }

    /**
     * Create an instance of {@link CanDownloadResponseListe }
     * 
     */
    public CanDownloadResponseListe createCanDownloadResponseListe() {
        return new CanDownloadResponseListe();
    }

    /**
     * Create an instance of {@link CapabilitiesListe }
     * 
     */
    public CapabilitiesListe createCapabilitiesListe() {
        return new CapabilitiesListe();
    }

    /**
     * Create an instance of {@link FileListe }
     * 
     */
    public FileListe createFileListe() {
        return new FileListe();
    }

    /**
     * Create an instance of {@link FormatListe }
     * 
     */
    public FormatListe createFormatListe() {
        return new FormatListe();
    }

    /**
     * Create an instance of {@link OrderListe }
     * 
     */
    public OrderListe createOrderListe() {
        return new OrderListe();
    }

    /**
     * Create an instance of {@link OrderAreaListe }
     * 
     */
    public OrderAreaListe createOrderAreaListe() {
        return new OrderAreaListe();
    }

    /**
     * Create an instance of {@link OrderLineListe }
     * 
     */
    public OrderLineListe createOrderLineListe() {
        return new OrderLineListe();
    }

    /**
     * Create an instance of {@link OrderReceiptListe }
     * 
     */
    public OrderReceiptListe createOrderReceiptListe() {
        return new OrderReceiptListe();
    }

    /**
     * Create an instance of {@link ProjectionListe }
     * 
     */
    public ProjectionListe createProjectionListe() {
        return new ProjectionListe();
    }

    /**
     * Create an instance of {@link VersionResponseListe }
     * 
     */
    public VersionResponseListe createVersionResponseListe() {
        return new VersionResponseListe();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "Area")
    public JAXBElement<AreaType> createArea(AreaType value) {
        return new JAXBElement<AreaType>(_Area_QNAME, AreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CanDownloadRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "CanDownloadRequest")
    public JAXBElement<CanDownloadRequestType> createCanDownloadRequest(CanDownloadRequestType value) {
        return new JAXBElement<CanDownloadRequestType>(_CanDownloadRequest_QNAME, CanDownloadRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CanDownloadResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "CanDownloadResponse")
    public JAXBElement<CanDownloadResponseType> createCanDownloadResponse(CanDownloadResponseType value) {
        return new JAXBElement<CanDownloadResponseType>(_CanDownloadResponse_QNAME, CanDownloadResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CapabilitiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "Capabilities")
    public JAXBElement<CapabilitiesType> createCapabilities(CapabilitiesType value) {
        return new JAXBElement<CapabilitiesType>(_Capabilities_QNAME, CapabilitiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "File")
    public JAXBElement<FileType> createFile(FileType value) {
        return new JAXBElement<FileType>(_File_QNAME, FileType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormatType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "Format")
    public JAXBElement<FormatType> createFormat(FormatType value) {
        return new JAXBElement<FormatType>(_Format_QNAME, FormatType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "Order")
    public JAXBElement<OrderType> createOrder(OrderType value) {
        return new JAXBElement<OrderType>(_Order_QNAME, OrderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderAreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "OrderArea")
    public JAXBElement<OrderAreaType> createOrderArea(OrderAreaType value) {
        return new JAXBElement<OrderAreaType>(_OrderArea_QNAME, OrderAreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderLineType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "OrderLine")
    public JAXBElement<OrderLineType> createOrderLine(OrderLineType value) {
        return new JAXBElement<OrderLineType>(_OrderLine_QNAME, OrderLineType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderReceiptType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "OrderReceipt")
    public JAXBElement<OrderReceiptType> createOrderReceipt(OrderReceiptType value) {
        return new JAXBElement<OrderReceiptType>(_OrderReceipt_QNAME, OrderReceiptType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProjectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "Projection")
    public JAXBElement<ProjectionType> createProjection(ProjectionType value) {
        return new JAXBElement<ProjectionType>(_Projection_QNAME, ProjectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "VersionResponse")
    public JAXBElement<VersionResponseType> createVersionResponse(VersionResponseType value) {
        return new JAXBElement<VersionResponseType>(_VersionResponse_QNAME, VersionResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkListeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "_links", scope = VersionResponseType.class)
    public JAXBElement<LinkListeType> createVersionResponseTypeLinks(LinkListeType value) {
        return new JAXBElement<LinkListeType>(_VersionResponseTypeLinks_QNAME, LinkListeType.class, VersionResponseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkListeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "_links", scope = ProjectionType.class)
    public JAXBElement<LinkListeType> createProjectionTypeLinks(LinkListeType value) {
        return new JAXBElement<LinkListeType>(_VersionResponseTypeLinks_QNAME, LinkListeType.class, ProjectionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileListe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "files", scope = OrderReceiptType.class)
    public JAXBElement<FileListe> createOrderReceiptTypeFiles(FileListe value) {
        return new JAXBElement<FileListe>(_OrderReceiptTypeFiles_QNAME, FileListe.class, OrderReceiptType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkListeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "_links", scope = OrderReceiptType.class)
    public JAXBElement<LinkListeType> createOrderReceiptTypeLinks(LinkListeType value) {
        return new JAXBElement<LinkListeType>(_VersionResponseTypeLinks_QNAME, LinkListeType.class, OrderReceiptType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderAreaListe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "areas", scope = OrderLineType.class)
    public JAXBElement<OrderAreaListe> createOrderLineTypeAreas(OrderAreaListe value) {
        return new JAXBElement<OrderAreaListe>(_OrderLineTypeAreas_QNAME, OrderAreaListe.class, OrderLineType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormatListe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "formats", scope = OrderLineType.class)
    public JAXBElement<FormatListe> createOrderLineTypeFormats(FormatListe value) {
        return new JAXBElement<FormatListe>(_OrderLineTypeFormats_QNAME, FormatListe.class, OrderLineType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProjectionListe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "projections", scope = OrderLineType.class)
    public JAXBElement<ProjectionListe> createOrderLineTypeProjections(ProjectionListe value) {
        return new JAXBElement<ProjectionListe>(_OrderLineTypeProjections_QNAME, ProjectionListe.class, OrderLineType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkListeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "_links", scope = OrderLineType.class)
    public JAXBElement<LinkListeType> createOrderLineTypeLinks(LinkListeType value) {
        return new JAXBElement<LinkListeType>(_VersionResponseTypeLinks_QNAME, LinkListeType.class, OrderLineType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkListeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "_links", scope = OrderAreaType.class)
    public JAXBElement<LinkListeType> createOrderAreaTypeLinks(LinkListeType value) {
        return new JAXBElement<LinkListeType>(_VersionResponseTypeLinks_QNAME, LinkListeType.class, OrderAreaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkListeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "_links", scope = OrderType.class)
    public JAXBElement<LinkListeType> createOrderTypeLinks(LinkListeType value) {
        return new JAXBElement<LinkListeType>(_VersionResponseTypeLinks_QNAME, LinkListeType.class, OrderType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkListeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "_links", scope = FormatType.class)
    public JAXBElement<LinkListeType> createFormatTypeLinks(LinkListeType value) {
        return new JAXBElement<LinkListeType>(_VersionResponseTypeLinks_QNAME, LinkListeType.class, FormatType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "name", scope = FileType.class)
    public JAXBElement<String> createFileTypeName(String value) {
        return new JAXBElement<String>(_FileTypeName_QNAME, String.class, FileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "fileId", scope = FileType.class)
    public JAXBElement<String> createFileTypeFileId(String value) {
        return new JAXBElement<String>(_FileTypeFileId_QNAME, String.class, FileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "metadataUuid", scope = FileType.class)
    public JAXBElement<String> createFileTypeMetadataUuid(String value) {
        return new JAXBElement<String>(_FileTypeMetadataUuid_QNAME, String.class, FileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "area", scope = FileType.class)
    public JAXBElement<String> createFileTypeArea(String value) {
        return new JAXBElement<String>(_FileTypeArea_QNAME, String.class, FileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "coordinates", scope = FileType.class)
    public JAXBElement<String> createFileTypeCoordinates(String value) {
        return new JAXBElement<String>(_FileTypeCoordinates_QNAME, String.class, FileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "projection", scope = FileType.class)
    public JAXBElement<String> createFileTypeProjection(String value) {
        return new JAXBElement<String>(_FileTypeProjection_QNAME, String.class, FileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "format", scope = FileType.class)
    public JAXBElement<String> createFileTypeFormat(String value) {
        return new JAXBElement<String>(_FileTypeFormat_QNAME, String.class, FileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "status", scope = FileType.class)
    public JAXBElement<String> createFileTypeStatus(String value) {
        return new JAXBElement<String>(_FileTypeStatus_QNAME, String.class, FileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkListeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "_links", scope = FileType.class)
    public JAXBElement<LinkListeType> createFileTypeLinks(LinkListeType value) {
        return new JAXBElement<LinkListeType>(_VersionResponseTypeLinks_QNAME, LinkListeType.class, FileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkListeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "_links", scope = CapabilitiesType.class)
    public JAXBElement<LinkListeType> createCapabilitiesTypeLinks(LinkListeType value) {
        return new JAXBElement<LinkListeType>(_VersionResponseTypeLinks_QNAME, LinkListeType.class, CapabilitiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "message", scope = CanDownloadResponseType.class)
    public JAXBElement<String> createCanDownloadResponseTypeMessage(String value) {
        return new JAXBElement<String>(_CanDownloadResponseTypeMessage_QNAME, String.class, CanDownloadResponseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkListeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "_links", scope = CanDownloadResponseType.class)
    public JAXBElement<LinkListeType> createCanDownloadResponseTypeLinks(LinkListeType value) {
        return new JAXBElement<LinkListeType>(_VersionResponseTypeLinks_QNAME, LinkListeType.class, CanDownloadResponseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkListeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "_links", scope = CanDownloadRequestType.class)
    public JAXBElement<LinkListeType> createCanDownloadRequestTypeLinks(LinkListeType value) {
        return new JAXBElement<LinkListeType>(_VersionResponseTypeLinks_QNAME, LinkListeType.class, CanDownloadRequestType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProjectionListe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "projections", scope = AreaType.class)
    public JAXBElement<ProjectionListe> createAreaTypeProjections(ProjectionListe value) {
        return new JAXBElement<ProjectionListe>(_OrderLineTypeProjections_QNAME, ProjectionListe.class, AreaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormatListe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "formats", scope = AreaType.class)
    public JAXBElement<FormatListe> createAreaTypeFormats(FormatListe value) {
        return new JAXBElement<FormatListe>(_OrderLineTypeFormats_QNAME, FormatListe.class, AreaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkListeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0", name = "_links", scope = AreaType.class)
    public JAXBElement<LinkListeType> createAreaTypeLinks(LinkListeType value) {
        return new JAXBElement<LinkListeType>(_VersionResponseTypeLinks_QNAME, LinkListeType.class, AreaType.class, value);
    }

}
