//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.05 at 08:37:03 AM CEST 
//


package no.geonorge.skjema.sosi.tjenestespesifikasjon.nedlastingapi._2;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VersionResponseListe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VersionResponseListe"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="versionresponse" type="{http://skjema.geonorge.no/SOSI/tjenestespesifikasjon/nedlastingapi/2.0}VersionResponseType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VersionResponseListe", propOrder = {
    "versionresponse"
})
public class VersionResponseListe
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected List<VersionResponseType> versionresponse;

    /**
     * Gets the value of the versionresponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the versionresponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVersionresponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VersionResponseType }
     * 
     * 
     */
    public List<VersionResponseType> getVersionresponse() {
        if (versionresponse == null) {
            versionresponse = new ArrayList<VersionResponseType>();
        }
        return this.versionresponse;
    }

}
