package no.geonorge.nedlasting.data.auto;

import org.apache.cayenne.CayenneDataObject;

import no.geonorge.nedlasting.data.DownloadOrder;

/**
 * Class _DownloadItem was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DownloadItem extends CayenneDataObject {

    public static final String SRID_PROPERTY = "srid";
    public static final String URL_PROPERTY = "url";
    public static final String ORDER_PROPERTY = "order";

    public static final String ORDER_ITEM_ID_PK_COLUMN = "ORDER_ITEM_ID";

    public void setSrid(Integer srid) {
        writeProperty(SRID_PROPERTY, srid);
    }
    public Integer getSrid() {
        return (Integer)readProperty(SRID_PROPERTY);
    }

    public void setUrl(String url) {
        writeProperty(URL_PROPERTY, url);
    }
    public String getUrl() {
        return (String)readProperty(URL_PROPERTY);
    }

    public void setOrder(DownloadOrder order) {
        setToOneTarget(ORDER_PROPERTY, order, true);
    }

    public DownloadOrder getOrder() {
        return (DownloadOrder)readProperty(ORDER_PROPERTY);
    }


}
