package no.geonorge.nedlasting.data.auto;

import org.apache.cayenne.CayenneDataObject;

import no.geonorge.nedlasting.data.DownloadOrder;

/**
 * Class _DownloadExternalJob was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DownloadExternalJob extends CayenneDataObject {

    public static final String COORDINATES_PROPERTY = "coordinates";
    public static final String FORMAT_PROPERTY = "format";
    public static final String JOB_ID_PROPERTY = "jobId";
    public static final String SRID_PROPERTY = "srid";
    public static final String ORDER_PROPERTY = "order";

    public static final String JOB_ID_PK_COLUMN = "JOB_ID";
    public static final String ORDER_ID_PK_COLUMN = "ORDER_ID";

    public void setCoordinates(String coordinates) {
        writeProperty(COORDINATES_PROPERTY, coordinates);
    }
    public String getCoordinates() {
        return (String)readProperty(COORDINATES_PROPERTY);
    }

    public void setFormat(String format) {
        writeProperty(FORMAT_PROPERTY, format);
    }
    public String getFormat() {
        return (String)readProperty(FORMAT_PROPERTY);
    }

    public void setJobId(String jobId) {
        writeProperty(JOB_ID_PROPERTY, jobId);
    }
    public String getJobId() {
        return (String)readProperty(JOB_ID_PROPERTY);
    }

    public void setSrid(Integer srid) {
        writeProperty(SRID_PROPERTY, srid);
    }
    public Integer getSrid() {
        return (Integer)readProperty(SRID_PROPERTY);
    }

    public void setOrder(DownloadOrder order) {
        setToOneTarget(ORDER_PROPERTY, order, true);
    }

    public DownloadOrder getOrder() {
        return (DownloadOrder)readProperty(ORDER_PROPERTY);
    }


}
