package no.geonorge.nedlasting.data.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import no.geonorge.nedlasting.data.DatasetFile;

/**
 * Class _Projection was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Projection extends CayenneDataObject {

    public static final String CODESPACE_PROPERTY = "codespace";
    public static final String NAME_PROPERTY = "name";
    public static final String SRID_PROPERTY = "srid";
    public static final String FILES_PROPERTY = "files";

    public static final String SRID_PK_COLUMN = "SRID";

    public void setCodespace(String codespace) {
        writeProperty(CODESPACE_PROPERTY, codespace);
    }
    public String getCodespace() {
        return (String)readProperty(CODESPACE_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setSrid(Integer srid) {
        writeProperty(SRID_PROPERTY, srid);
    }
    public Integer getSrid() {
        return (Integer)readProperty(SRID_PROPERTY);
    }

    public void addToFiles(DatasetFile obj) {
        addToManyTarget(FILES_PROPERTY, obj, true);
    }
    public void removeFromFiles(DatasetFile obj) {
        removeToManyTarget(FILES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DatasetFile> getFiles() {
        return (List<DatasetFile>)readProperty(FILES_PROPERTY);
    }


}
