//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.05 at 08:37:03 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kxml.no/rest/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package no.kxml.rest._1;
